name: Publish Docker image
on: [push]
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Get Time
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 0
          format: 'YYYYMMDDHHmmss'
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          password: '${{ secrets.DOCKER_PASSWORD }}'
          username: '${{ secrets.DOCKER_USERNAME }}'
      - id: meta
        name: 'Extract metadata (tags, labels) for Docker'
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: diegorubin/lifeguard
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          labels: '${{ steps.meta.outputs.labels }}'
          push: true
          tags: 'diegorubin/lifeguard:${{ steps.time.outputs.time }}'
      - name: Update application resource
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: 29684009
          repo: diegorubin/diegorubindev-projects
          token: ${{ secrets.PERSONAL_TOKEN }}
          inputs: '{ "application": "lifeguard", "imageTag": "${{ steps.time.outputs.time }}" }'
